#cloud-config
ssh_pwauth: true
hostname: debian12-base

users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: false

  - name: root
    lock_passwd: true
    ssh-authorized-keys: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPs/hWAelf2ahoRid1xEPs75fecE/bci0Lt3RI6Feqpk berk@berk
    shell: /bin/bash

packages:
  - qemu-guest-agent
  - vim
  - htop
  - curl
  - ncdu
  - net-tools

runcmd:
  - echo 'export PS1="\[\e[38;5;48m\]\u\[\e[m\]\[\e[38;5;141m\]@\[\e[38;5;206m\]\h\[\e[38;5;203m\][\$(hostname -I | awk '\''{print \$1}'\'')]\e[m\]\[\e[38;5;215m\] \w\[\e[38;5;141m\] > \[\e[m\]"' >> /home/debian/.bashrc
  - echo 'export PS1="\[\e[38;5;48m\]\u\[\e[m\]\[\e[38;5;141m\]@\[\e[38;5;206m\]\h\[\e[38;5;203m\][\$(hostname -I | awk '\''{print \$1}'\'')]\e[m\]\[\e[38;5;215m\] \w\[\e[38;5;141m\] > \[\e[m\]"' >> /root/.bashrc
